# Get Data dari database dan cek masa berlaku Token
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNUmlmcWlhbmRpIiwiZW1haWwiOiJhbmRpQGdtYWlsLmNvbSIsImlhdCI6MTcyMTc0Nzk0MSwiZXhwIjoxNzIxNzQ3OTU2fQ.eEO9Lw5bU1AxmtUr_Kf-LhTf8B77UAsRaAHFoushIWQ


###

#Tambah Data
POST http://localhost:5000/users
Content-Type: application/json

{
    "email" : "andi@gmail.com",
    "password" : "12345"
}

###

#Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "andi@gmail.com",
    "password" : "12345"
}


###
# Refresh Token Baru
GET http://localhost:5000/token


###

#Logout
DELETE  http://localhost:5000/logout
